In [4]:
import numpy as np
import pandas as pd

import matplotlib.pyplot as plt
%matplotlib inline

In [5]:
df=pd.read_csv('perrin-freres-monthly-champagne-.csv')
df.head()

     Month  Perrin Freres monthly champagne sales millions ?64-?72
0  1964-01                                             2815.0
1  1964-02                                             2672.0
2  1964-03                                             2755.0
3  1964-04                                             2721.0
4  1964-05                                             2946.0

In [6]:
df.tail()

,Month,Perrin Freres monthly champagne sales millions ?64-?72
102,1972-07,4298.0
103,1972-08,1413.0
104,1972-09,5877.0
105,NaN,NaN
106,Perrin Freres monthly champagne sales millions...,NaN

In [7]:
df_cleaned = df.dropna(axis=1)

In [13]:
df_cleaned.tail()

Empty DataFrame
Columns: []
Index: [102, 103, 104, 105, 106]

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 107 entries, 0 to 106
Empty DataFrame